[tool.black]
line-length = 88
target-versions = ['py38']
skip-string-normalization = true

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.flake8]
max-line-length = 88
extend-ignore = 'E203,W503,F401'
exclude = '.git,__pycache__,tmp'
